import {test,expect} from '../../web/node_modules/@playwright/test/index';
test('admin publishes sanitized statements and edits both languages',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('Integration-password-123');await page.getByRole('button',{name:'Sign in'}).click();
 await expect(page.getByRole('heading',{name:'Find your next challenge.'})).toBeVisible();await page.getByRole('button',{name:'Authoring',exact:true}).click();await page.getByRole('button',{name:'+ New problem'}).click();
 const title='Browser sample '+Date.now();const definition={title,statement:'## A safe statement\nReturn the input. <img src=x onerror="window.pwned=true"><script>window.pwned=true</script>',difficulty:'easy',tags:['browser'],signature:{method:'echo',params:[{name:'value',ty:'string'}],returns:'string'},limits:{time_ms:2000,memory_mib:256,output_bytes:1048576},tests:[{args:['你好'],expected:'你好',hidden:false},{args:['secret-hidden-case'],expected:'secret-hidden-case',hidden:true}]};
 await page.getByLabel('Problem definition (JSON)').fill(JSON.stringify(definition));await page.getByRole('button',{name:'Preview statement'}).click();await expect(page.getByRole('heading',{name:'A safe statement'})).toBeVisible();expect(await page.evaluate(()=>(window as any).pwned)).toBeUndefined();await page.getByRole('button',{name:'Validate & publish'}).click();await expect(page.getByRole('status')).toContainText('Published immutable version');
 await page.getByRole('button',{name:'Problems',exact:true}).click();await page.getByLabel('Search problems').fill(title);await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:new RegExp(title)}).click();await expect(page.getByRole('heading',{name:title})).toBeVisible();await expect(page.locator('.monaco-editor').first()).toBeVisible();await expect(page.getByRole('button',{name:'▷ Run'})).toBeEnabled({timeout:45000});
 await page.getByLabel('Language',{exact:true}).selectOption('python');await expect(page.locator('.monaco-editor').first()).toContainText('def echo');await page.getByLabel('Language',{exact:true}).selectOption('cpp');await expect(page.locator('.monaco-editor').first()).toContainText('class Solution');expect(await page.locator('body').textContent()).not.toContain('secret-hidden-case');expect(await page.evaluate(()=>(window as any).pwned)).toBeUndefined();
 await page.screenshot({path:'/tmp/practice-editor.png',fullPage:true});expect(errors).toEqual([]);
});
test('regular user solves in Python and C++ with semantic completion',async({page})=>{
 test.skip(process.env.TEST_RUNNER!=='1','Requires deployed gVisor worker and editor services');
 const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:18080';
 await page.goto('/');await page.getByLabel('Username',{exact:true}).fill('admin');await page.getByLabel('Password',{exact:true}).fill('Integration-password-123');await page.getByRole('button',{name:'Sign in'}).click();await expect(page.getByRole('button',{name:'Authoring',exact:true})).toBeVisible();
 const me=await (await page.request.get('/api/v1/session')).json();const student='browser'+Date.now();const headers={'Origin':origin,'X-CSRF-Token':me.csrf};
 expect((await page.request.post('/api/v1/admin/users',{headers,data:{username:student,password:'Browser-student-password'}})).status()).toBe(201);
 const problem={title:'Solve echo '+Date.now(),statement:'Return the input.',difficulty:'easy',tags:['acceptance'],signature:{method:'echo',params:[{name:'value',ty:'string'}],returns:'string'},limits:{time_ms:2000,memory_mib:256,output_bytes:1048576},tests:[{args:['hello'],expected:'hello',hidden:false},{args:['private unicode 🦀'],expected:'private unicode 🦀',hidden:true}]};
 const draft=await (await page.request.post('/api/v1/admin/problems',{headers,data:problem})).json();expect((await page.request.post(`/api/v1/admin/problems/${draft.id}/publish`,{headers})).ok()).toBeTruthy();await page.getByRole('button',{name:'Sign out'}).click();await page.getByLabel('Username',{exact:true}).fill(student);await page.getByLabel('Password',{exact:true}).fill('Browser-student-password');await page.getByRole('button',{name:'Sign in'}).click();await page.getByRole('button',{name:new RegExp(problem.title)}).click();await expect(page.locator('.monaco-editor').first()).toBeVisible();
 for(const language of ['python','cpp']){
  await page.getByLabel('Language',{exact:true}).selectOption(language);await expect(page.getByRole('status')).toContainText('Semantic completion connected',{timeout:45000});
  await page.locator('.monaco-editor').first().click();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(language==='python'?'class Solution:\n    def echo(self, value: str) -> str:\n        return value':'#include <string>\nclass Solution { public: std::string echo(std::string value) { return value; } };');
  await page.getByRole('button',{name:'Submit →'}).click();await expect(page.locator('.results h3')).toContainText('accepted',{timeout:60000});await expect(page.locator('.results h3')).toContainText('2 / 2');
 }
});
