import {test} from './account-fixtures';
import {expect} from '../../web/node_modules/@playwright/test/index';

test('themed dropdown keyboard, dismissal, theme, and horizontal switches',async({page})=>{
 await page.route('**/api/v1/session',route=>route.fulfill({json:{id:'student',username:'student',admin:false,csrf:'test'}}));
 await page.route('**/api/v1/problems?*',route=>route.fulfill({json:[]}));
 await page.goto('/');
 const difficulty=page.getByRole('combobox',{name:'Difficulty',exact:true});
 await difficulty.focus();await difficulty.press('ArrowDown');
 await expect(page.getByRole('listbox',{name:'Difficulty options'})).toBeVisible();
 await difficulty.press('End');await difficulty.press('Enter');
 await expect(difficulty).toHaveAttribute('data-value','hard');
 await expect(difficulty).toBeFocused();
 await difficulty.press('ArrowDown');await difficulty.press('Home');await difficulty.press('Escape');
 await expect(difficulty).toHaveAttribute('data-value','hard');
 await difficulty.press('ArrowDown');await difficulty.press('e');await difficulty.press('Enter');
 await expect(difficulty).toHaveAttribute('data-value','easy');
 await difficulty.click();await difficulty.press('Tab');
 await expect(difficulty).toHaveAttribute('aria-expanded','false');
 await difficulty.click();await page.getByRole('heading',{name:'Problems',exact:true}).click();
 await expect(difficulty).toHaveAttribute('aria-expanded','false');
 await page.getByLabel('User menu').click();
 const semantic=page.getByRole('button',{name:'Disable semantic completion'});
 await expect(semantic).toHaveAttribute('aria-pressed','true');await semantic.click();
 await expect(page.getByRole('button',{name:'Enable semantic completion'})).toHaveAttribute('aria-pressed','false');
 const pause=page.getByRole('button',{name:'Pause background animation'});
 await pause.click();await expect(pause).toHaveAttribute('aria-pressed','true');
 const theme=page.getByRole('combobox',{name:'Theme',exact:true});
 await theme.click();await page.getByRole('option',{name:'Dark',exact:true}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await theme.click();
 const popup=page.getByRole('listbox',{name:'Theme options'});
 expect(await popup.evaluate(node=>getComputedStyle(node).backgroundColor)).toBe('rgb(25, 25, 28)');
 await page.screenshot({path:'/tmp/j0coder-themed-dropdown-dark.png'});
 await theme.press('Escape');
 await page.setViewportSize({width:375,height:900});await theme.click();
 const bounds=await popup.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(375);
 await page.screenshot({path:'/tmp/j0coder-themed-dropdown-mobile.png'});
});
