apiVersion: v1
kind: Service
metadata: {name: {{ .Release.Name }}-api, namespace: {{ .Release.Namespace }}}
spec:
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: api}
  ports: [{name: http, port: 8080, targetPort: http}]
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Release.Name }}-editor, namespace: {{ .Release.Namespace }}}
spec:
  selector: {app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/component: editor}
  ports: [{name: http, port: 8081, targetPort: http}]
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tlsSecret }}
  tls: [{hosts: [{{ $.Values.ingress.host }}], secretName: {{ . }} }]
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /editor
            pathType: Prefix
            backend: {service: {name: {{ .Release.Name }}-editor, port: {number: 8081}}}
          - path: /
            pathType: Prefix
            backend: {service: {name: {{ .Release.Name }}-api, port: {number: 8080}}}
{{- end }}
